# This workflow builds a project afters tests including e2e and deploys to Rancher using Docker image
# For more information see:
#  - https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#  - https://github.com/marketplace/actions/build-and-push-docker-images

name: CI and CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      - name: Test with NPM
        run: |
          npm ci
          export CHROME_BIN=chromium-browser
          npm run lint
          npm run network > /dev/null &
          while ! nc -z localhost 8545; do sleep 5; done
          npm run soltest
          npm run migrate
          npm run e2e
          npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: success() && ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        if: success() && ${{ github.event_name == 'push' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            rhizomik/copyrightly:${{ github.sha }}
            rhizomik/copyrightly:latest
